config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  get '/about_us' => "home#about_us"
  get '/solutions' => "home#solutions"
  get '/clients' => "home#clients"
  get 'contact_us' => "home#contact_us"
  post 'send_enquiry' => "home#send_enquiry"
  get '/privacy_policy' => "home#privacy_policy"
  get '/terms-and-conditions' => "home#terms_and_conditions"
  get '/refund-policy' => "home#refund_policy"
  get '/cancellation-policy' => "home#cancellation_policy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attachment.rb
class Attachment < ApplicationRecord
    belongs_to :service
    enum attachment_type: {image:0,video:1}
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :client_testimonials
end

app/models/client_testimonial.rb
class ClientTestimonial < ApplicationRecord
  belongs_to :client

  validates :client_id, presence: true
end

app/models/feature.rb
class Feature < ApplicationRecord
    belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
    has_many :attachments
    has_many :features
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about_us
  end

  def solutions
  end

  def clients
  end

  def contact_us
  end

  def send_enquiry
    Notifier.enquiry(params).deliver_now!
    redirect_to contact_us_path
  end

  def privacy_policy
  end

  def terms_and_conditions
  end

  def refund_policy
  end

  def cancellation_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    if request.path == path
      return 'active'
    else
      return ''
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/cancellation_policy.html.haml
%div.ss-page-content.d-flex.flex-column.flex-1
  .card.ss-card.border-0.flex-1
    .card-body.d-grid.gap-5.px-4.py-5.p-lg-5
      %div
        %h2.fw-bold.text-primary.mb-4 Cancellation Policy
        %div.client-list.d-flex.flex-wrap
          %p.mb-0 
            SimplySmart services are offered on a subscription basis, which may include a one-time hardware investment (e.g., water meters) and an ongoing yearly subscription for access to features such as water consumption data and alerts. If you wish to cancel your subscription, you must contact your society's management committee directly
          %p.mb-0 In case the society management committee wishes to cancel the services on behalf of the entire society, they can raise a cancellation request with SimplySmart. Upon receiving such a request, SimplySmart will process the cancellation for all users associated with the society.

          %p.mb-0 Please note that SimplySmart does not manage individual subscriptions or payments. Any cancellation requests, whether raised by individuals or the society management committee, must be coordinated through the society. SimplySmart is not responsible for handling refunds or financial disputes related to subscription fees after the cancellation is processed.

app/views/home/clients.html.haml
%div.ss-page-content.d-flex.flex-column.flex-1
  .card.ss-card.border-0.flex-1
    .card-body.d-grid.gap-5.px-4.py-5.p-lg-5
      %div
        %h2.fw-bold.text-primary.mb-4 Clients
        %div.client-list.d-flex.flex-wrap.justify-content-center
          %div.client-list-item.d-flex.align-items-center.justify-content-center
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("embassy", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("gmr", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("windchimes", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("gtc", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("hilife", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("ace", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("abacus", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("alliance", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("capitaland", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("manas", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("prasannatech", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("pride", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("padmaj", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("ums", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("urdhvam", :alt => "mobile", class: "img-fluid")
          %div.client-list-item
            .client-item.shadow.d-flex.align-items-center.justify-content-center.p-3 
              = image_tag("scrum", :alt => "mobile", class: "img-fluid")

app/views/home/contact_us.html.haml
%div.ss-page-content.d-flex.flex-column.flex-1
  .card.ss-card.border-0.flex-1
    .card-body.d-grid.gap-5.px-4.py-5.p-lg-5
      %div
        %h2.fw-bold.text-primary.mb-4 Contact Us
        %div.row.gy-5.gy-lg-0
          %div.col-md-6
            .card.border.border-primary
              .card-body
                %form.d-grid.gap-4(gutter="2" action="/send_enquiry" method="post")
                  %div.d-flex.flex-column.flex-xl-row.gap-3
                    %div.form-group.flex-1
                      %label.text-primary.fw-bold(for="full-name") Full Name
                      %input#full-name.form-control(type="text" name="full_name" required)
                    
                    %div.form-group.flex-1
                      %label.text-primary.fw-bold(for="subject") Subject
                      %input#subject.form-control(type="text" name="subject" required)
                    
                  %div.d-flex.flex-column.flex-xl-row.gap-3
                    %div.form-group.flex-1
                      %label.text-primary.fw-bold(for="email") Email
                      %input#email.form-control(type="email" name="email" required)
                    
                    %div.form-group.flex-1
                      %label.text-primary.fw-bold(for="mobile-no") Mobile Number
                      %input#mobile-no.form-control(type="tel" name="mobile_no" required)

                  %div
                    %div.form-group
                      %label.text-primary.fw-bold(for="message") Message
                      %textarea#message.form-control(name="message" required)
                  %div.text-center 
                    %input.btn.btn-primary.text-white.px-4(type="submit" value="Submit")
          %div.col-md-6
            %div.d-grid.gap-3.h-100
              .card.border.border-primary
                .card-body
                  %div
                    %h4.text-primary.fw-bold.mb-3 Pune:
                    %p.mb-0 6th Floor, Amar Tech Park, Patil Nagar, Balewadi, Pune, Maharashtra – 411045
                    %p.mb-0 Phone: +91 9916784858
              .card.border.border-primary
                .card-body
                  %div
                    %h4.text-primary.fw-bold.mb-3 Bengaluru:
                    %p.mb-0 No. 932, 1st Floor, 1st Main Road, AECS Layout, B-Block, Singasandra, Bengaluru 560 068
                    %p.mb-0 Phone: +91 9916784858
                

app/views/home/index.html.haml
%div.ss-page-content.d-flex.flex-column.flex-1
  .card.ss-card.border-0.flex-1
    .card-body.d-grid.gap-5.px-0.py-5
      %div.d-flex.flex-column.flex-lg-row.gap-3.gap-lg-5.ps-lg-5
        %div.flex-1.px-3.px-lg-0
          %h2.fw-bold.text-primary What is SimplySmart?
          %p.mb-0 SimplySmart is an effective water management tool for residential and commercial projects. It comprises a water meter with a data recorder and transmitter, plus a cloud-based software platform that provides information on water consumption and data on several other parameters. When you opt for the SimplySmart water metering solution, you have to make a one-time investment in the Water Meter, whereas access to water consumption-related data is provided on a yearly subscription basis
        %div.flex-1
          %div{style: "border-radius: 15px; padding: 20px; overflow: hidden; "}
            %iframe{width: "560", height: "315", src: "https://www.youtube.com/embed/KxqUDM_ylaA?si=i_hfv_fVh0-5QTTH", title: "YouTube video player", frameborder: "0", allow: "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share", referrerpolicy: "strict-origin-when-cross-origin", allowfullscreen: true}

      %div.d-flex.flex-column.flex-lg-row.gap-3.gap-lg-5.px-3.px-lg-5
        %div.flex-1.order-2.order-lg-0
          = image_tag("ss-meters", :alt => "meters", :class => "w-100")      
        %div.flex-1
          %h2.fw-bold.text-primary SimplySmart Water Meters
          %p.mb-0 
            We provide 
            %span.text-secondary three 
            options for water meters viz., Piston type and Ultrasonic type. Both have proven performance records. SimplySmart water meters are easy to install and can be considered during new plumbing or can even be fitted with the existing plumbing at each inlet point. 
      %div.d-flex.flex-column.flex-lg-row.gap-3.gap-lg-5.px-3.px-lg-5
        %div.flex-1
          %h2.fw-bold.text-primary Managing water was never so easy before!
          %p.mb-0 SimplySmart offers water meters and a cloud-based software platform to record the water data, which can be accessed via PC or even a smartphone. Once the meters are operational, your township is allotted a separate account on the dedicated web server of SimplySmart, ensuring a high level of security. You can access the data of all the users, get real-time alerts and timely insights to manage water or initiate relevant actions, such as ordering tankers. Using this user-friendly software you can also generate bills for individual users that can be automatically sent via email or WhatsApp. Individual users can access their own consumption data via a mobile app. This helps them to understand their usage pattern and exercise control on water usage as well as know the leakages, if any. Our experience shows that the 'Pay for what is used' model creates a great sense of accountability and at some places, has helped reduce water
        %div.flex-1
          = image_tag("ss-laptop", :alt => "laptop", :class => "w-100") 
      %div.px-0.px-lg-5
        %h2.fw-bold.text-primary.text-center.mb-4 What Benefits does SimplySmart offer?
        %ul.benefits-list-wrap.list-unstyled.mb-0.p-0.d-flex.flex-wrap.gap-3.justify-content-center
          %li.benefits-list-item.border.border-primary.d-flex.align-items-center.text-center.fw-bold 
            100% Automation that works for you
          %li.benefits-list-item.border.border-primary.d-flex.align-items-center.text-center.fw-bold 
            Comprehensive water management dashboard
          %li.benefits-list-item.border.border-primary.d-flex.align-items-center.text-center.fw-bold 
            Real-time water leakage alerts
          %li.benefits-list-item.border.border-primary.d-flex.align-items-center.text-center.fw-bold 
            Dependable and remotely operable control valve
          %li.benefits-list-item.border.border-primary.d-flex.align-items-center.text-center.fw-bold 
            Daily health diagnostics of the complete system
          %li.benefits-list-item.border.border-primary.d-flex.align-items-center.text-center.fw-bold 
            Unique wired and wireless architecture
          %li.benefits-list-item.border.border-primary.d-flex.align-items-center.text-center.fw-bold 
            Guaranteed peace of mind



  

app/views/home/privacy_policy.html.haml
%div.ss-page-content.d-flex.flex-column.flex-1
  .card.ss-card.border-0.flex-1
    .card-body.d-grid.gap-5.px-4.py-5.p-lg-5
      %div
        %h2.fw-bold.text-primary.mb-4 Privacy Policy
        %div.client-list.d-flex.flex-wrap
          %p.mb-0 Welcome to SimplySmart Technologies Pvt. Ltd, a provider of comprehensive water management solutions for residential and commercial projects. This Privacy Policy outlines how we collect, use, and safeguard your personal data when you interact with our website, mobile app, and services. By using SimplySmart’s services, you agree to the practices described in this policy.

          %div
            %h2.text-primary Information SimplySmart Collects
            %p.mb-0 At SimplySmart, we collect two types of information:
            %div
              %li 
                %strong Personal Information: 
                This includes your name, email address, mailing address, phone number, and payment details such as credit card information.
              %li 
                %strong Non-Personal Information: 
                This covers technical data, including browser type, operating system, IP address, and Internet service provider. It’s important to note that we do not use cookies to track user behavior on our website or mobile app.
          %div
            %h2.text-primary  How the Information is Collected
            %p.mb-0 Information is collected through the following methods:
            %div
              %li 
                %strong Directly from You: 
                This occurs when you sign up, place orders, or communicate with SimplySmart.
              %li 
                %strong Automatically: 
                Water usage data is collected by SimplySmart water meters and transmitted securely using the MQTT protocol with TLS encryption.
              %li 
                %strong Third-Party Services: 
                We utilize Cloud for hosting and third-party payment gateways for payment processing. However, SimplySmart directly manages the data collected by these services
          
          %div
            %h2.text-primary  Why the Information is Collected
            %p.mb-0 The primary purposes for which SimplySmart collects information include:
            %div
              %li Providing water consumption insights and analytics
              %li Improving the performance of SimplySmart’s services.
              %li Managing billing and subscriptions.
              %li Fulfilling society management requirements, such as enabling/disabling billing features or leakage alerts.
            
          %div
            %h2.text-primary  User Privacy Controls
            %p.mb-0 SimplySmart offers flexibility in data and service options based on society management preferences, rather than individual users. Some privacy control features include:
            %div
              %li 
                %strong Feature Control: 
                Billing or leakage alert services can be enabled or disabled based on society management decisions.
              %li 
                %strong Opt-Out Options: 
                Individual residents can request to opt out of certain features through their society management team.
            
          %div
            %h2.text-primary  Sharing Your Information and Disclosures
            %p.mb-0 At SimplySmart, we do not share personal information for marketing purposes. Information may only be shared in the following cases:
            %div
              %li 
                %strong Third-Party Service Providers: 
                Data is shared with service providers for hosting and payment gateways for processing transactions..
              %li 
                %strong Legal Requirements: 
                Data may be disclosed when required by law or to comply with legal processes.
          
          %div
            %h2.text-primary  Your Information Security
            %p.mb-0 We take your information security seriously at SimplySmart, employing robust measures to protect your data, including:
            %div
              %li 
                %strong SSL Encryption: 
                All communication between our site/app and your device is encrypted using HTTPS.
              %li 
                %strong MQTT Protocol with TLS: 
                Data from water meters is securely transmitted using MQTT with TLS encryption.
          
          %div
            %h2.text-primary  Your Information Retention and Deletion
            %p.mb-0 In terms of data retention, SimplySmart follows these guidelines:
            %div
              %li 
                %strong Raw Data: 
                Retained for 60 days to support operational needs.
              %li 
                %strong Aggregated Data: 
                Retained for up to 1 year for analytics and reporting.
            %p.mb-0 In the event that a society or user requests data deletion, SimplySmart will comply in accordance with legal and operational obligations.

          %div
            %h2.text-primary  Role and Details of Data Protection Officer (DPO)
            %p.mb-0 SimplySmart Technologies Pvt. Ltd has a dedicated Data Protection Officer (DPO) responsible for overseeing data privacy and security. For any questions or concerns, you can contact the DPO at:
            %ul 
              %strong Data Protection Officer
            %ul SimplySmart Technologies Pvt. Ltd
            %ul 
              %a{href: "mailto:info@simplysmart.tech"} info@simplysmart.tech
        
        %hr
        %div
          %p.mb-0 By using SimplySmart’s services, you acknowledge and consent to the practices outlined in this privacy policy. If you have any questions or require clarification on any aspect of this policy, please feel free to contact us.

app/views/home/refund_policy.html.haml
%div.ss-page-content.d-flex.flex-column.flex-1
  .card.ss-card.border-0.flex-1
    .card-body.d-grid.gap-5.px-4.py-5.p-lg-5
      %div
        %h2.fw-bold.text-primary.mb-4 Refund Policy
        %div.client-list.d-flex.flex-wrap
          %p.mb-0 
            SimplySmart services are provided on a subscription basis, which may include access to water consumption data, alerts, and other features. Please be aware that using SimplySmart services might require a one-time investment in hardware (e.g., water meters) and an ongoing yearly subscription. 
            %strong Payments related to water usage are processed securely through a third-party payment gateway and transferred directly to the respective society's accounts.

          %p.mb-0 As SimplySmart does not manage or hold payments, any requests for refunds or disputes regarding payments must be directed to your society's management committee. SimplySmart is not responsible for processing refunds or resolving any financial disputes related to payments made to society accounts.

app/views/home/solutions.html.haml
%div.ss-page-content.d-flex.flex-column.flex-1  
  .card.ss-card.border-0.flex-1
    .card-body.d-grid.gap-5.px-4.py-5.p-lg-5
      %div
        %h2.fw-bold.text-primary.mb-4 SimplySmart Water Meters
        %p.mb-0 
          We provide 
          %span.text-secondary three 
          options for water meters viz., Piston type and Ultrasonic type. Both have proven performance records. SimplySmart water meters are easy to install and can be considered during new plumbing or can even be fitted with the existing plumbing at each inlet point.
      %div.d-flex.flex-column.flex-xl-row.gap-4
        %div.flex-1
          = image_tag("water-meter1", :alt => "water meter", :class => "d-block meter-img mx-auto mb-4 text-center") 
          %h5.text-secondary.fw-bold Flow ON
          %h5.fw-bold Piston Type Water Meter
          %ul.mb-0.ps-3
            %li FlowON Piston Type Water Meter with an added advantage of a Valve
            %li Electrically actuated Ball Valve for DN 15, DN 20 & DN 25 connections
            %li Brass body with Stainless steel ball material to withstand harsh conditions 
            %li Works on 24 V DC supply
            %li The meter with a valve setup can be used for a prepaid mode. The valve closes when a fixed volume of water passes through the meter
            %li It can be used to control the leakages 
            %li Get a better control of your water usage
        %div.flex-1
          = image_tag("water-meter2", :alt => "water meter", :class => "d-block meter-img mx-auto mb-4 text-center") 
          %h5.text-secondary.fw-bold FlowON PREPAID
          %h5.fw-bold Piston Type Water Meter
          %ul.mb-0.ps-3
            %li Unique grooved piston fitted in the measuring chamber of the meter almost nullifies the chances of stoppages
            %li Co-polymer resin body can withstand even hard water
            %li High level of accuracy
            %li High durability and reliable performance in accordance with ISO 4064
            %li Type tested and certified by FCRI, Palakkad
            %li Available in sizes DN 15, DN 20 & DN 25 
            %li Electronics housed in a separate box
            %li Battery life – 10 years (Li-ion battery)
        %div.flex-1
          = image_tag("water-meter3", :alt => "water meter", :class => "d-block meter-img mx-auto mb-4 text-center") 
          %h5.text-secondary.fw-bold DWM
          %h5.fw-bold Ultrasonic Water Meter
          %ul.mb-0.ps-3
            %li Based on ultrasound principle. Uses ultrasonic transducers and acoustic reflectors 
            %li High level of accuracy
            %li Supports IoT-ready wireless communication
            %li Robust construction and reliable electronics for a long life
            %li Compact design. Can fit in confined, narrow spaces of existing plumbing
            %li Available in sizes from DN 15 to DN 40
            %li Battery life – 10 years (Li-ion battery) 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Simplysmart Technolgies Pvt Ltd
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    %meta{:name => "description", :content => "Discover SimplySmart, the powerful water management tool for both residential and commercial projects. Get real-time data on water consumption and other important parameters with our innovative water meter, data recorder, and cloud-based software platform. Invest in the SimplySmart water metering solution and enjoy access to vital water consumption data with a yearly subscription."}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    = favicon_link_tag asset_path('logo')
  %body
    %header.ss-header.bg-white
      #nav-bar 
        = render partial:'shared/navbar'
    %main.ss-main-section.d-flex.flex-column.flex-1
      %section.ss-carousel-section
        = render partial:'shared/carousel'
      %section.ss-content-section.d-flex.flex-column.flex-1
        = yield
    = render partial: 'shared/footer'

app/views/notifier/enquiry.html.haml
%strong Name:
%p= @params[:full_name]
%strong Contact:
%p= @params[:mobile_no]
%strong Email:
%p= @params[:email]
%strong Message:
%p= @params[:message]

app/views/shared/_carousel.html.haml
#ssCarousel.carousel.slide.h-100.ss-carousel{"data-bs-ride" => "carousel"}
  .carousel-inner.h-100
    .carousel-item.active.h-100
      %div.d-flex.flex-column.flex-lg-row
        %div.heading-box
          %h1.carousel-heading.mb-5.mb-lg-0.pt-5.fw-bold Install water meters in every apartment
        %div.carousel-img-wrap.d-flex.align-items-center.justify-content-center
          = image_tag("building-slider", :alt => "slider", :class => "carousel-slider-img")
    .carousel-item.h-100
      %div.d-flex.flex-column.flex-lg-row
        %div.heading-box
          %h1.carousel-heading.mb-5.mb-lg-0.pt-5.fw-bold Comprehensive water management dashboard
        %div.carousel-img-wrap.d-flex.align-items-center.justify-content-center
          = image_tag("comperhensive-slider", :alt => "slider", :class => "carousel-slider-img")
    .carousel-item.h-100
      %div.d-flex.flex-column.flex-lg-row
        %div.heading-box
          %h1.carousel-heading.mb-5.mb-lg-0.pt-5.fw-bold Real-time water leakage alerts
        %div.carousel-img-wrap.d-flex.align-items-center.justify-content-center
          = image_tag("real-time-slider", :alt => "slider", :class => "carousel-slider-img")
    .carousel-item.h-100
      %div.d-flex.flex-column.flex-lg-row
        %div.heading-box
          %h1.carousel-heading.mb-5.mb-lg-0.pt-5.fw-bold Dependable and remotely operable control valve
        %div.carousel-img-wrap.d-flex.align-items-center.justify-content-center
          = image_tag("remote-control-slider", :alt => "slider", :class => "carousel-slider-img")
    .carousel-item.h-100
      %div.d-flex.flex-column.flex-lg-row
        %div.heading-box
          %h1.carousel-heading.mb-5.mb-lg-0.pt-5.fw-bold Daily health diagnostics of the complete system
        %div.carousel-img-wrap.d-flex.align-items-center.justify-content-center
          = image_tag("dignostics-slider", :alt => "slider", :class => "carousel-slider-img")              

app/views/shared/_footer.html.haml
%footer.d-flex.justify-content-between
  .d-flex.align-items-center
    .copyright Copyright © 2023 SimplySmart Technologies Private Limited
  .d-flex
    %a{href: "/terms-and-conditions", class: "px-2 px-lg-4 py-1 py-lg-0"} Terms and Conditions
    %a{href: "/privacy_policy", class: "px-2 px-lg-4 py-1 py-lg-0"} Privacy Policy
    %a{href: "/refund-policy", class: "px-2 px-lg-4 py-1 py-lg-0"} Refund Policy
    %a{href: "/cancellation-policy", class: "px-2 px-lg-4 py-1 py-lg-0"} Cancellation Policy

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.p-3  
  %a.navbar-brand.px-5.py-0.me-0{:href => "/"}
    = image_tag("logo", :alt => "logo", :class => "ss-site-logo")
  %button.navbar-toggler{"aria-controls" => "navbarScroll", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarScroll", "data-bs-toggle" => "collapse", type: "button", :class => "border-0"}
    %span.navbar-toggler-icon
  #navbarScroll.collapse.navbar-collapse.ss-navbar
    %ul.navbar-nav.ms-auto.my-2.my-lg-0.navbar-nav-scroll
      %li.nav-item
        %a{"aria-current" => "page", href: "/", class: "nav-link px-2 px-lg-4 py-1 py-lg-0 #{active_class(root_path)}"} Home
      %li.nav-item
        %a{href: "/solutions", class: "nav-link px-2 px-lg-4 py-1 py-lg-0 #{active_class(solutions_path)}"} Solutions
      %li.nav-item
        %a{href: "/clients", class: "nav-link px-2 px-lg-4 py-1 py-lg-0 #{active_class(clients_path)}"} Clients
      %li.nav-item
        %a{href: "/contact_us", class: "nav-link px-2 px-lg-4 py-1 py-lg-0 #{active_class(contact_us_path)}"} Contact Us